language: node_js
node_js:
- 15.5.1
cache: npm

install:
- npm install

script:
- yarn test 
- yarn run build

deploy:
provider: pages
github-token: $GITHUB_TOKEN
local_dir: build 
on:
  branch: gh-pages